export const anchors = [
  {
    id: "a1",
    title: "Home",
    active: true,
    href: "/",
    special: false,
    colStart: 1,
    colEnd: 2,
    link: 0,
  },
  {
    id: "a2",
    title: "About",
    active: false,
    href: "/about",
    special: false,
    colStart: 2,
    colEnd: 3,
    link: 1,
  },
  {
    id: "a3",
    title: "Business",
    active: false,
    href: "/business",
    special: false,
    colStart: 3,
    colEnd: 4,
    link: 2,
  },
  {
    id: "a4",
    title: "Products",
    active: false,
    href: "/products",
    special: false,
    colStart: 4,
    colEnd: 5,
    link: 3,
  },
  {
    id: "a5",
    title: "Subsidiaries",
    active: false,
    href: "/subsidiaries",
    special: false,
    colStart: 5,
    colEnd: 6,
    link: 4,
  },
  {
    id: "a6",
    title: "Blog",
    active: false,
    href: "/blog",
    special: false,
    colStart: 6,
    colEnd: 7,
    link: 5,
  },
  {
    id: "a7",
    title: "Contact Us",
    active: false,
    href: "/contact",
    special: true,
    colStart: 7,
    colEnd: 8,
    link: 6,
  },
];
