'use client'

export default function Head() {
  return (
    <>
      <title>FreshCo</title>
      <meta name="color-scheme" content="light only" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        precedence="default"
        href="https://fonts.cdnfonts.com/css/austria"
        rel="stylesheet"
      />
    </>
  )
}
